server:
  port: 8081
spring:
  datasource:
#      url: "jdbc:mysql://localhost:3306/identity_service"
#      username: root
#      password: root
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_POST}
      timeout: 50000

jwt:
  secret-key: "czX5dveubFQAGGPF1XHU5nfhOY1anSc47VDkfcEc11mmGJDPThK9v6I1Da1sTerJ6IB0SxrJnnThYljq1jd1S4CMF7IqJpUxlOmWsiXLxwg="
  access:
    expire: 3600
  refresh:
    expire: 7200